name = "ElectronGas"
uuid = "8c98e03e-8755-48b1-a5ef-1e2e7812a7c9"
authors = ["Kun Chen"]
version = "0.1.0"

[deps]
CompositeGrids = "b5136c89-beeb-4521-9139-60d2cac8be56"
Cuba = "8a292aeb-7a57-582c-b821-06e4c11590b1"
GreenFunc = "9efc7ea6-d529-4241-ab29-dcf68b94af7c"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
Lehmann = "95bf888a-8996-4655-9f35-1c0506bdfefe"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CompositeGrids = "0.0"
Cuba = "2"
GreenFunc = "0.1"
LegendrePolynomials = "0.3"
Lehmann = "0.1, 0.2"
Parameters = "0.12"
Roots = "2"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
